### ISSUE TITLE
Find cool css template 

### ISSUE THREAD

**Issue by LordDarkula** [LHSCyberSecurityClub/lhscybersecurityclub.github.io#3]

**Comment by vikranth22446** [comment]
This is really Important!!@!!

**Comment by vikranth22446** [comment]
http://www.infinitytechnologies.com.au/

**Comment by vikranth22446** [comment]
[Boss Free Website Template - Free-CSS.com.zip](https://github.com/LHSCyberSecurityClub/lhscybersecurityclub.io/files/465613/Boss.Free.Website.Template.-.Free-CSS.com.zip)
